### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [Jackhhooker/prj-rev-bwfs-dasmoto#5]
It is best to simplify the CSS code as much as possible for shared properties. Several properties like the font-weight are also shared. In addition, any property you give to the universal selector is applied to all elements, so you do not need to apply it again for each element. You can simplify the code like so

```css
* {
  font-family: Helvetica;
  font-weight:bold;
}
.header {
  font-size: 100px;  
  color: khaki;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
}
h2, .price {
  font-size: 32px;
  color: white;
}
.brushes {
  background-color: mediumspringgreen;
}
.frames {  
  background-color: lightcoral;
}
.paint {  
  background-color: skyblue;
}
.price {
  color: blue;  
}
```
